# Generated by Django 5.1.7 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_category_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
